---
title: Keep Calm and Carry On
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Yous
description: Minimal, responsive Jekyll theme for hackers.
baseurl: ''
url: https://qmaruf.github.io
lang: en
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- README.md
- LICENSE.txt
- CHANGELOG.md
- jekyll-whiteglass.gemspec
- screenshot.png
- vendor
twitter_username: maruf_q
twitter_image: 
facebook_app_id: 
facebook_image: 
google_analytics: UA-20160176-2
comments: false
remote_theme: yous/whiteglass
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap
markdown: kramdown
excerpt_separator: "<!-- more -->"
permalink: "/:year/:month/:day/:title/"
paginate_path: "/posts/:num/"
paginate: 5
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: category_archives
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
future: true
